### ISSUE TITLE
ISSUE

### ISSUE THREAD

**Issue by rensraiken** [felixbrandt/colorbot#4]
# DIESER BOT
IST FARBENFROH
ADDE RGB UND SO
HSL UND HSW
SONST KILL ICH DICH FELIX B.

**Comment by rensraiken** [comment]
![kmk74](https://cloud.githubusercontent.com/assets/17089254/21616621/6bf5e774-d1e2-11e6-9210-41c96f327e76.png)

**Comment by rensraiken** [comment]
![xtdz9](https://cloud.githubusercontent.com/assets/17089254/21616682/c118a4e4-d1e2-11e6-980a-2881bd7e26a4.png)

**Comment by rensraiken** [comment]
![uttj9](https://cloud.githubusercontent.com/assets/17089254/21616737/0775b814-d1e3-11e6-9626-48c21f93ed5a.png)

**Comment by rensraiken** [comment]
![9wl50](https://cloud.githubusercontent.com/assets/17089254/21616815/5ac410e2-d1e3-11e6-9230-c6f5b632eea0.png)

**Comment by rensraiken** [comment]
![8md15](https://cloud.githubusercontent.com/assets/17089254/21616874/9c5d677e-d1e3-11e6-8736-b988f47c305e.png)

**Comment by felixbrandt** [comment]
siehe #1 und #2
